.TH DUNGEONBASH 6 2009-09-19 "Martin Read" "Martin's Dungeon Bash User Manual"

.SH NAME

dungeonbash \- Martin's Dungeon Bash, a simple roguelike game.

.SH SYNOPSIS

.B dungeonbash 

.SH DESCRIPTION

Martin's Dungeon Bash is a simple roguelike game. Unlike most of the genre,
there is no victory condition defined; the player's sole objective is to kill
monsters, amass gold, and dive ever deeper into the dungeon.

In-game help for the user interface is available, and must be maintained
regardless of the existence of the man page; as such, user interface
documentation is not provided here.

.SH "SEE ALSO"

dungeonbashrc(5)

.SH BUGS

Usually numerous. Please consult the official web site for the current list of
known bugs.

If you are using a pre-built binary of Martin's Dungeon Bash provided by a
third party, you should direct your bug reports through them.

If you are using a modified version of Martin's Dungeon Bash, do not submit
your bug reports to me unless you can reproduce the bug in an unmodified
version of the program.

When submitting bug reports, please provide suitable information. In
particular, if you see an error message, include the text of the error message
in your bug report.

.SH AUTHOR

Martin's Dungeon Bash, and this manual page, were written by Martin Read
<mpread@chiark.greenend.org.uk>

