/* This file is automatically generated and is not the preferred form for making
 * modifications to the work. */

#define PERMONS_CC
#include "pmon1.hh"
Permon permons[] =
{
{
    "adventurer", "adventurers",
    "An omnicidal maniac bent on exterminating everyone who might obstruct his relentless quest for treasure.",
    Species_own, PMSYM_HUMAN, DBCLR_WHITE,
    100, 1, 20,
    { 5, 5, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    0, 0, 0, SPEED_NORMAL, 0 | PMF_MEATY | PMF_STUPID
},
{
    "smith", "smiths",
    "An innocent artisan, devoid of any malice.",
    Species_own, PMSYM_HUMAN, DBCLR_CYAN,
    100, 0, 1,
    { 0, 0, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    0, 0, 0, SPEED_NORMAL, 0 | PMF_MEATY | PMF_RESIST_FIRE | PMF_PEACEFUL | PMF_SMART
},
{
    "newt", "newts",
    "An amphibious creature of unusual size.",
    Species_own, PMSYM_NEWT, DBCLR_RED,
    20, 1, 3,
    { 0, 2, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    1, 0, 1, SPEED_SLOW, 0 | PMF_MEATY | PMF_STUPID
},
{
    "rat", "rats",
    "The rats here are the kind that eat cats.",
    Species_own, PMSYM_RODENT, DBCLR_BROWN,
    15, 1, 4,
    { 0, 2, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    4, 0, 2, SPEED_FAST, 0 | PMF_MEATY | PMF_STUPID
},
{
    "wolf", "wolves",
    "What a wolf is doing in a mysterious hole in the ground is anyone's guess.",
    Species_own, PMSYM_CANINE, DBCLR_BROWN,
    30, 6, 20,
    { 8, 10, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    6, 0, 15, SPEED_FAST, 0 | PMF_MEATY
},
{
    "snake", "snakes",
    "Long, slithery, venomous.",
    Species_own, PMSYM_SNAKE, DBCLR_RED,
    20, 6, 15,
    { 10, 3, 20, Maux_poison_body, 10 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    9, 0, 40, SPEED_FAST, 0 | PMF_STUPID | PMF_MEATY
},
{
    "human", "humans",
    "You know what a human is, right?",
    Species_human, PMSYM_HUMAN, DBCLR_BROWN,
    100, 1, 8,
    { 5, 5, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    0, 0, 0, SPEED_NORMAL, 0 | PMF_MEATY
},
{
    "thug", "thugs",
    "An unpleasant person in leather, carrying a blunt instrument.",
    Species_human, PMSYM_THUG, DBCLR_BROWN,
    30, 1, 8,
    { 5, 5, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    4, 0, 5, SPEED_NORMAL, 0 | PMF_ARMED | PMF_MEATY
},
{
    "goon", "goons",
    "A particularly unpleasant person in leather, carrying a blunt instrument.",
    Species_human, PMSYM_THUG, DBCLR_BROWN,
    20, 3, 20,
    { 6, 10, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 10, SPEED_NORMAL, 0 | PMF_ARMED | PMF_MEATY
},
{
    "hunter", "hunters",
    "A talented, but somewhat amoral, bowman.",
    Species_human, PMSYM_HUNTER, DBCLR_GREEN,
    30, 9, 40,
    { 6, 6, 0, Maux_none, 0 }, { 20, 10, DT_PHYS, "shoots an arrow", 0, Raux_none, 0 },
    10, 0, 50, SPEED_NORMAL, 0 | PMF_ARCHER | PMF_MEATY | PMF_ARMED
},
{
    "sybarite", "sybarites",
    "A devoted shrine-guardian, naked save for a simple leather sword-harness.",
    Species_human, PMSYM_PRIEST, DBCLR_L_PURPLE,
    100, 6, 40,
    { 20, 10, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    10, 0, 60, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED
},
{
    "iron priest", "iron priests",
    "A devoted shrine-guardian, armoured in massive steel.",
    Species_human, PMSYM_PRIEST, DBCLR_CYAN,
    100, 6, 40,
    { 20, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    20, 0, 100, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED | PMF_RESIST_FIRE | PMF_RESIST_COLD
},
{
    "slime priest", "slime priests",
    "A devoted shrine-guardian, bloated and disfigured by pestilence.",
    Species_human, PMSYM_PRIEST, DBCLR_CYAN,
    100, 6, 40,
    { 20, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    5, 0, 40, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_RESIST_POIS
},
{
    "fire priest", "fire priests",
    "A devoted shrine-guardian, robed and cowled in vivid scarlet.",
    Species_human, PMSYM_PRIEST, DBCLR_CYAN,
    100, 6, 40,
    { 20, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 100, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED | PMF_RESIST_FIRE
},
{
    "death priest", "death priests",
    "A devoted shrine-guardian, mailed and skull-masked.",
    Species_human, PMSYM_PRIEST, DBCLR_CYAN,
    100, 6, 40,
    { 20, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 100, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED | PMF_RESIST_COLD | PMF_RESIST_POIS | PMF_RESIST_NECR
},
{
    "duellist", "duellists",
    "A masterful swordsman.",
    Species_human, PMSYM_FIGHTER, DBCLR_RED,
    40, 12, 60,
    { 30, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 130, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED
},
{
    "warlord", "warlords",
    "A skilled and tenacious warrior, well armed to deal with visiting maniacs.",
    Species_human, PMSYM_FIGHTER, DBCLR_L_RED,
    30, 15, 80,
    { 25, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    20, 0, 400, SPEED_NORMAL, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED
},
{
    "wizard", "wizards",
    "A student of the Arcane.",
    Species_human, PMSYM_WIZARD, DBCLR_BLUE,
    80, 12, 40,
    { 10, 10, 0, Maux_none, 0 }, { 20, 10, DT_ELEC, "casts", 0, Raux_none, 0 },
    15, 0, 200, SPEED_NORMAL, 0 | PMF_SMART | PMF_MAGICIAN | PMF_MEATY
},
{
    "archmage", "archmagi",
    "A master of the Arcane.",
    Species_human, PMSYM_WIZARD, DBCLR_L_BLUE,
    80, 24, 80,
    { 15, 15, 0, Maux_none, 0 }, { 30, 15, DT_ELEC, "casts", 0, Raux_none, 0 },
    15, 0, 1500, SPEED_NORMAL, 0 | PMF_SMART | PMF_MAGICIAN | PMF_MEATY
},
{
    "goblin", "goblins",
    "A skulking, grey-skinned humanoid.",
    Species_own, PMSYM_GOBLIN, DBCLR_BROWN,
    20, 1, 6,
    { 1, 3, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    3, 0, 3, SPEED_NORMAL, 0 | PMF_ARMED | PMF_MEATY
},
{
    "elf", "elves",
    "A tall and uncannily slender humanoid.",
    Species_elf, PMSYM_ELF, DBCLR_L_GREY,
    100, 3, 15,
    { 10, 6, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 15, SPEED_FAST, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED
},
{
    "bad elf", "bad elves",
    "Banished from the elven homelands for sadism even they could not tolerate.",
    Species_own, PMSYM_ELF, DBCLR_L_GREY,
    40, 3, 15,
    { 10, 6, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 15, SPEED_FAST, 0 | PMF_SMART | PMF_MEATY | PMF_ARMED
},
{
    "troll", "trolls",
    "A twisted humanoid figure taller than a tall man, with leathery green hide and long limbs.",
    Species_own, PMSYM_TROLL, DBCLR_GREEN,
    20, 12, 80,
    { 15, 15, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    13, 0, 150, SPEED_NORMAL, 0 | PMF_STUPID | PMF_MEATY
},
{
    "giant", "giants",
    "A humanoid twice or more a man's height, noted for its strength but not its wits.",
    Species_giant, PMSYM_GIANT, DBCLR_BROWN,
    20, 21, 80,
    { 15, 25, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    20, 0, 500, SPEED_NORMAL, 0 | PMF_STUPID | PMF_MEATY | PMF_ARMED
},
{
    "giant jarl", "giant jarls",
    "A humanoid twice or more a man's height, possessed of rather more wit than his kin.",
    Species_giant, PMSYM_GIANT, DBCLR_L_GREY,
    80, 25, 160,
    { 20, 30, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    22, 0, 1000, SPEED_NORMAL, 0 | PMF_MEATY | PMF_ARMED
},
{
    "zombie", "zombies",
    "A perambulatory cadaver; you'll probably have to hack it to bits to stop it.",
    Species_own, PMSYM_ZOMBIE, DBCLR_L_GREY,
    25, 3, 30,
    { 2, 12, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    1, 0, 7, SPEED_SLOW, 0 | PMF_STUPID | PMF_UNDEAD | PMF_RESIST_COLD | PMF_MEATY | PMF_NOCORPSE
},
{
    "wraith", "wraiths",
    "The ghostly remnant of a past adventurer, filled with a terrible hunger for living souls.",
    Species_own, PMSYM_WRAITH, DBCLR_WHITE,
    25, 12, 40,
    { 25, 5, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    5, 0, 100, SPEED_SLOW, 0 | PMF_SMART | PMF_UNDEAD | PMF_RESIST_COLD | PMF_MEATY | PMF_ETHEREAL | PMF_ALWAYS_NEUTER
},
{
    "lich", "liches",
    "A long-dead student of foul sorcery whose obsession with knowledge quickens his withered frame.",
    Species_own, PMSYM_LICH, DBCLR_L_GREY,
    70, 15, 70,
    { 15, 15, 0, Maux_none, 0 }, { 25, 15, DT_NECRO, "casts", 0, Raux_none, 0 },
    15, 0, 250, SPEED_NORMAL, 0 | PMF_SMART | PMF_UNDEAD | PMF_RESIST_COLD | PMF_MAGICIAN | PMF_SKELETAL | PMF_NOCORPSE
},
{
    "master lich", "master liches",
    "A long-dead master of foul sorcery, armed with the very power of death itself.",
    Species_own, PMSYM_LICH, DBCLR_PURPLE,
    60, 30, 150,
    { 30, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    30, 0, 3000, SPEED_NORMAL, 0 | PMF_SMART | PMF_UNDEAD | PMF_RESIST_COLD | PMF_MAGICIAN | PMF_SKELETAL | PMF_NOCORPSE
},
{
    "vampire", "vampires",
    "A blood-drinking horror that was once a man.",
    Species_own, PMSYM_VAMPIRE, DBCLR_RED,
    55, 18, 70,
    { 25, 15, 30, Maux_drink_blood, 10 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    22, 0, 750, SPEED_NORMAL, 0 | PMF_SMART | PMF_UNDEAD | PMF_RESIST_COLD | PMF_MEATY | PMF_NOCORPSE
},
{
    "imp", "imps",
    "An annoying minor demon.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_RED,
    80, 6, 40,
    { 25, 8, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 20, SPEED_FAST, 0 | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_NOCORPSE | PMF_TELE_HARASS
},
{
    "iron snake", "iron snakes",
    "A slithering mechanical abomination in the service of the Lords of Iron.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_CYAN,
    100, 9, 40,
    { 25, 12, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    12, 0, 40, SPEED_FAST, 0 | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_COLD | PMF_NOCORPSE
},
{
    "foetid ooze", "foetid oozes",
    "A hell-spawned blob of festering corruption.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_L_GREEN,
    100, 9, 40,
    { 25, 6, 30, Maux_decay, 10 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    8, 0, 30, SPEED_NORMAL, 0 | PMF_DEMONIC | PMF_RESIST_POIS | PMF_RESIST_ACID | PMF_NOCORPSE | PMF_ALWAYS_NEUTER
},
{
    "lasher", "lashers",
    "A many-tentacled fiend.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_L_PURPLE,
    100, 9, 35,
    { 25, 3, 30, Maux_hentacle, 1 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 50, SPEED_FAST, 0 | PMF_DEMONIC | PMF_NOCORPSE | PMF_ALWAYS_OTHER
},
{
    "hellhound", "hellhounds",
    "A vaguely dog-like thing from the Inferno, belching stinking flames.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_RED,
    100, 9, 35,
    { 25, 10, 0, Maux_none, 0 }, { 15, 8, DT_FIRE, "breathes", 0, Raux_none, 0 },
    12, 0, 50, SPEED_NORMAL, 0 | PMF_DEMONIC | PMF_NOCORPSE | PMF_RESIST_FIRE | PMF_ALWAYS_NEUTER
},
{
    "flying skull", "flying skulls",
    "A disembodied skull propelled by some malicious spirit of the Necropolis.",
    Species_own, PMSYM_LESSER_DEMON, DBCLR_WHITE,
    100, 9, 35,
    { 25, 10, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    12, 0, 40, SPEED_NORMAL, 0 | PMF_DEMONIC | PMF_NOCORPSE | PMF_RESIST_COLD | PMF_RESIST_POIS | PMF_RESIST_NECR | PMF_RESIST_ELEC | PMF_SKELETAL | PMF_ALWAYS_NEUTER
},
{
    "ironguard", "ironguards",
    "The massively armed legionaries of the Halls of Iron.",
    Species_own, PMSYM_MIDDLE_DEMON, DBCLR_CYAN,
    70, 18, 60,
    { 30, 25, 20, Maux_shieldbreaker, 1 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 500, SPEED_SLOW, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_COLD | PMF_NOCORPSE
},
{
    "festering horror", "festering horrors",
    "A man-shaped mound of filth vomited up from some unspeakable Hell.",
    Species_own, PMSYM_MIDDLE_DEMON, DBCLR_L_GREEN,
    70, 18, 60,
    { 25, 20, 30, Maux_fever, 10 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    10, 0, 500, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_POIS | PMF_RESIST_ACID | PMF_NOCORPSE | PMF_ALWAYS_NEUTER
},
{
    "flayer", "flayers",
    "A gaunt humanoid with scythe-like blades where its hands should be.",
    Species_own, PMSYM_MIDDLE_DEMON, DBCLR_L_PURPLE,
    70, 18, 50,
    { 30, 25, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 500, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_POIS | PMF_NOCORPSE | PMF_ALWAYS_NEUTER
},
{
    "scorcher", "scorchers",
    "A muscular scarlet-skinned humanoid wreathed in fire and smoke.",
    Species_own, PMSYM_MIDDLE_DEMON, DBCLR_RED,
    70, 18, 50,
    { 30, 25, 5, Maux_ignite, 10 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 500, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_NOCORPSE
},
{
    "reaper", "reapers",
    "A perambulatory skeleton with darkness blazing in its eyes, armed with a wickedly sharp scythe.",
    Species_own, PMSYM_MIDDLE_DEMON, DBCLR_WHITE,
    70, 18, 50,
    { 30, 25, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    15, 0, 500, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_COLD | PMF_RESIST_POIS | PMF_RESIST_NECR | PMF_RESIST_ELEC | PMF_NOCORPSE | PMF_SKELETAL
},
{
    "iron lord", "iron lords",
    "A massively armoured slayer of heroes and armies alike, one of the lords and masters of the Halls of Iron.",
    Species_own, PMSYM_GREATER_DEMON, DBCLR_CYAN,
    75, 27, 200,
    { 40, 40, 20, Maux_shieldbreaker, 1 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    30, 0, 2000, SPEED_SLOW, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_COLD | PMF_NOCORPSE | PMF_GDEMON
},
{
    "defiler", "defilers",
    "A massively armoured slayer of heroes and armies alike, one of the lords and masters of the Halls of Iron.",
    Species_own, PMSYM_GREATER_DEMON, DBCLR_L_GREEN,
    75, 27, 120,
    { 30, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    25, 0, 2000, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_MAGICIAN | PMF_NOCORPSE | PMF_GDEMON
},
{
    "dominator", "dominators",
    "The lords and masters of the fleshy Hells, so devoted to the study of flesh that they experiment upon themselves.",
    Species_own, PMSYM_GREATER_DEMON, DBCLR_L_PURPLE,
    75, 27, 120,
    { 30, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    25, 0, 2000, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_MAGICIAN | PMF_NOCORPSE | PMF_GDEMON
},
{
    "immolator", "immolators",
    "To look upon this mighty fiend of the Inferno is to look upon the incarnate essence of Fire.",
    Species_own, PMSYM_GREATER_DEMON, DBCLR_RED,
    75, 27, 120,
    { 30, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    25, 0, 2000, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_MAGICIAN | PMF_NOCORPSE | PMF_GDEMON
},
{
    "deathlord", "deathlords",
    "Death given form, the keepers of the souls of the unrighteous, the lords of the Necropolis.",
    Species_own, PMSYM_GREATER_DEMON, DBCLR_WHITE,
    75, 27, 120,
    { 30, 20, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    25, 0, 2000, SPEED_NORMAL, 0 | PMF_SMART | PMF_DEMONIC | PMF_RESIST_FIRE | PMF_RESIST_COLD | PMF_RESIST_NECR | PMF_RESIST_POIS | PMF_RESIST_ELEC | PMF_MAGICIAN | PMF_NOCORPSE | PMF_GDEMON | PMF_SKELETAL
},
{
    "archdevil", "archdevils",
    "The mightiest among demons, to whose faces all others bow.",
    Species_own, PMSYM_ARCHDEVIL, DBCLR_PURPLE,
    100, 1000, 1,
    { 0, 0, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    25, 0, 2000, SPEED_NORMAL, 0 | PMF_NOCORPSE | PMF_GDEMON
},
{
    "centaur", "centaurs",
    "The wise man does not think too hard about the circumstances of a centaur's conception.",
    Species_own, PMSYM_CENTAUR, DBCLR_BROWN,
    30, 9, 40,
    { 15, 10, 0, Maux_none, 0 }, { -1, -1, DT_PHYS, "", 0, Raux_none, 0 },
    10, 0, 50, SPEED_FAST, 0 | PMF_MEATY
},
{
    "ice monster", "ice monsters",
    "A vaguely humanoid figure of living ice.",
    Species_own, PMSYM_ICE_MONSTER, DBCLR_WHITE,
    50, 6, 40,
    { 10, 15, 0, Maux_none, 0 }, { 20, 15, DT_COLD, "launches a blast of", 0, Raux_none, 0 },
    10, 0, 35, SPEED_SLOW, 0 | PMF_RESIST_COLD | PMF_ARCHER | PMF_NOCORPSE | PMF_ALWAYS_NEUTER
},
{
    "dragon", "dragons",
    "Of the very smallest sort, not even so large as an elephant. Its fire will burn you all the same.",
    Species_own, PMSYM_DRAGON, DBCLR_RED,
    50, 15, 80,
    { 20, 20, 0, Maux_none, 0 }, { 20, 20, DT_FIRE, "breathes", 0, Raux_none, 0 },
    18, 0, 300, SPEED_NORMAL, 0 | PMF_RESIST_FIRE | PMF_RESIST_POIS | PMF_ARCHER | PMF_MEATY
}
};
const int PM_COUNT = (sizeof permons) / (sizeof permons[0]);
